### ISSUE TITLE
Cannot read CEPAS / EZ-Link

### ISSUE THREAD

**Issue by sybond** [micolous/metrodroid#167]
## Description of the issue
Please see attached [log](https://github.com/micolous/metrodroid/files/2368972/metrodroid_cepas.log).

**Comment by phcoder** [comment]
Was it working before?  I'll prepare exploratory version. I'll read the standard again but I think it's silent on the issue of selection. (Yes, I bought the standard)

**Comment by micolous** [comment]
I'll have to leave this one with @phcoder.

If you want to see if #159 is a probable cause, you want to roll back to https://github.com/micolous/metrodroid/commit/efc06922066b70d50f9823ea008fdb7749810e3c

**Comment by sybond** [comment]
@phcoder working with latest release version.

**Comment by phcoder** [comment]
Please try the branch cepasexp: https://github.com/phcoder/metrodroid/tree/cepasexp

**Comment by sybond** [comment]
Here is the log:
```
09-17 09:43:40.722 18913-19043/au.id.micolous.farebot D/au.id.micolous.metrodroid.card.Card: Reading tag f2bb7264. 2 tech(s) supported:
    android.nfc.tech.IsoDep
    android.nfc.tech.NfcB
09-17 09:43:40.754 18913-19043/au.id.micolous.farebot W/DesfireCard: Card responded with invalid response, may not be DESFire?
    java.lang.IllegalArgumentException: Invalid response: 6d00
        at au.id.micolous.metrodroid.card.desfire.DesfireProtocol.sendRequest(DesfireProtocol.java:163)
        at au.id.micolous.metrodroid.card.desfire.DesfireProtocol.getManufacturingData(DesfireProtocol.java:73)
        at au.id.micolous.metrodroid.card.desfire.DesfireCard.dumpTag(DesfireCard.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:98)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.790 18913-19043/au.id.micolous.farebot D/au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol: Select file 4000
09-17 09:43:40.818 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 0
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.824 18913-18919/au.id.micolous.farebot I/zygote64: Compiler allocated 8MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
09-17 09:43:40.838 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 1
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.855 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 2
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.876 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 3
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6700
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.877 18913-18919/au.id.micolous.farebot I/zygote64: Do full code cache collection, code=107KB, data=87KB
09-17 09:43:40.878 18913-18919/au.id.micolous.farebot I/zygote64: After code cache collection, code=83KB, data=55KB
09-17 09:43:40.898 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 4
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.912 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 5
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.923 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 6
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.935 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 7
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.946 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 8
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.960 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 9
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.972 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 10
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.984 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 11
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:40.995 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 12
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:41.006 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 13
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:41.019 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 14
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:41.031 18913-19043/au.id.micolous.farebot W/CEPASProtocol: Error reading purse 15
    au.id.micolous.metrodroid.card.iso7816.ISO7816Exception: Got unknown result: 6b00
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:131)
        at au.id.micolous.metrodroid.card.cepas.CEPASProtocol.getPurse(CEPASProtocol.java:43)
        at au.id.micolous.metrodroid.card.cepas.CEPASApplication.dumpTag(CEPASApplication.java:109)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:106)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:41.032 18913-19043/au.id.micolous.farebot D/au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol: Select by name 315449432e494341
09-17 09:43:41.045 18913-19043/au.id.micolous.farebot E/au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol: couldn't select application
    java.io.FileNotFoundException
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:124)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.selectByName(ISO7816Protocol.java:142)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:112)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:41.046 18913-19043/au.id.micolous.farebot D/au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol: Select by name d4100000030001
09-17 09:43:41.061 18913-19043/au.id.micolous.farebot E/au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol: couldn't select application
    java.io.FileNotFoundException
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:124)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.selectByName(ISO7816Protocol.java:142)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:118)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:41.062 18913-19043/au.id.micolous.farebot D/au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol: Select by name 5041592e535a54
09-17 09:43:41.078 18913-19043/au.id.micolous.farebot E/au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol: couldn't select application
    java.io.FileNotFoundException
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.sendRequest(ISO7816Protocol.java:124)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Protocol.selectByName(ISO7816Protocol.java:142)
        at au.id.micolous.metrodroid.card.iso7816.ISO7816Card.dumpTag(ISO7816Card.java:123)
        at au.id.micolous.metrodroid.card.Card.dumpTag(Card.java:103)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:191)
        at au.id.micolous.metrodroid.activity.ReadingTagActivity$ReadingTagTask.doInBackground(ReadingTagActivity.java:182)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-17 09:43:41.132 18913-19043/au.id.micolous.farebot I/au.id.micolous.metrodroid.activity.ReadingTagActivity: Dumped card successfully!
09-17 09:43:41.132 18913-19043/au.id.micolous.farebot D/au.id.micolous.metrodroid.activity.ReadingTagActivity: XML: <card partial_read="false" scanned_at="1537152221084" id="f2bb7264" type="5">
    XML:    <applications/>
    XML: </card>
09-17 09:43:41.194 18913-18913/au.id.micolous.farebot I/Timeline: Timeline: Activity_launch_request time:28819623
09-17 09:43:41.356 18913-18913/au.id.micolous.farebot I/Timeline: Timeline: Activity_launch_request time:28819785
09-17 09:43:43.396 18913-18919/au.id.micolous.farebot I/zygote64: Do partial code cache collection, code=107KB, data=106KB
    After code cache collection, code=107KB, data=106KB
    Increasing code cache capacity to 512KB
09-17 09:43:43.397 18913-18919/au.id.micolous.farebot I/zygote64: Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()

```

**Comment by phcoder** [comment]
I updated cepasexp with another fix. Turns out that CEPAS is subtly different in zero-parameter commands (or our generic wrapper is wrong)
